from app.ingestion.embedder import generate_query_embedding
from app.retrieval.vector_store import retrieve_chunks
from app.generation.generator import generate_answer

def ask_question(question: str) -> str:
    """The entire RAG pipeline service

    Args:
        question (str): The question asked by the user

    Returns:
        str: The answer generated by the RAG pipeline
    """
    
    # 1. Convert the question into an embedding
    query_embedding = generate_query_embedding(question)
    
    # 2. Retrieve relevant chunks from ChromaDB
    results = retrieve_chunks(
        query_embedding=query_embedding,
        top_k=3
    )
    
    # 3. Extract the retrieved documents
    documents = results["documents"][0]
    
    # 4. Combine the documents into one context
    context = "\n\n".join(documents)
    
    # 5. Generate the final answer
    answer = generate_answer(
        question=question,
        context=context
    )
    
    return answer